//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FershGreen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.MedicalHistory = new HashSet<MedicalHistory>();
        }
    
        public int CusID { get; set; }
        public string CusName { get; set; }
        public string CusCard { get; set; }
        public string CusSex { get; set; }
        public string CusBirth { get; set; }
        public string CusNation { get; set; }
        public string CusMarriage { get; set; }
        public string CusAddress { get; set; }
        public string CusTelephone { get; set; }
        public string CusEmergency { get; set; }
        public string CusOccupation { get; set; }
        public string CusBloodType { get; set; }
        public string CusCulture { get; set; }
        public string CusDoctor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalHistory> MedicalHistory { get; set; }
    }
}
