//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FershGreen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspect
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inspect()
        {
            this.Conclusion = new HashSet<Conclusion>();
            this.Internal = new HashSet<Internal>();
            this.Surgery = new HashSet<Surgery>();
        }
    
        public int InID { get; set; }
        public string InDoctor { get; set; }
        public string InName { get; set; }
        public string InTime { get; set; }
        public string ConConclu { get; set; }
        public string ConDescribe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conclusion> Conclusion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Internal> Internal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Surgery> Surgery { get; set; }
    }
}
