//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FershGreen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KnowledgeBase
    {
        public int KnowID { get; set; }
        public string KnowCommon { get; set; }
        public string KnowType { get; set; }
        public string KnowAnswer { get; set; }
        public Nullable<System.DateTime> KnowAdd { get; set; }
        public Nullable<System.DateTime> KnowUp { get; set; }
        public string KnowPeople { get; set; }
    }
}
