//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FershGreen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnVisit
    {
        public int RetID { get; set; }
        public string RetName { get; set; }
        public string RetType { get; set; }
        public string RetIsomorphism { get; set; }
        public string Resul { get; set; }
        public Nullable<System.DateTime> RetTime { get; set; }
        public string RetPeople { get; set; }
    }
}
