//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FershGreen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserGood { get; set; }
        public string UserLogin { get; set; }
        public string UserPwd { get; set; }
        public Nullable<System.DateTime> UserBirth { get; set; }
        public string UserSex { get; set; }
        public string UserQua { get; set; }
    }
}
