//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FershGreen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppID { get; set; }
        public string AppName { get; set; }
        public Nullable<System.DateTime> AppDate { get; set; }
        public Nullable<System.DateTime> AppStart { get; set; }
        public Nullable<System.DateTime> AppEnd { get; set; }
        public string AppIsomorphism { get; set; }
        public Nullable<int> AppDD { get; set; }
    }
}
