//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FershGreen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Family = new HashSet<Family>();
            this.Marriage = new HashSet<Marriage>();
            this.MedicalHistory = new HashSet<MedicalHistory>();
            this.Menstrual = new HashSet<Menstrual>();
            this.Present = new HashSet<Present>();
        }
    
        public int CusID { get; set; }
        public string CusName { get; set; }
        public string CusCard { get; set; }
        public string CusSex { get; set; }
        public Nullable<System.DateTime> CusBirth { get; set; }
        public string CusMarriage { get; set; }
        public string CusNation { get; set; }
        public string CusAddress { get; set; }
        public string CusTelephone { get; set; }
        public string CusOccupation { get; set; }
        public string CusBloodType { get; set; }
        public string CusDoctor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Family> Family { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Marriage> Marriage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalHistory> MedicalHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menstrual> Menstrual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Present> Present { get; set; }
    }
}
