//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FershGreen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalHistory
    {
        public int MedID { get; set; }
        public string MedCategory { get; set; }
        public Nullable<System.DateTime> MedTime { get; set; }
        public string MedPlace { get; set; }
        public string MedSurvey { get; set; }
        public int MCusID { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
