//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FershGreen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menstrual
    {
        public int MenID { get; set; }
        public string MenCategory { get; set; }
        public Nullable<System.DateTime> MenTime { get; set; }
        public string MenPlace { get; set; }
        public string MenSurvey { get; set; }
        public int SCusID { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
