//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FershGreen.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrivateClinicEntities : DbContext
    {
        public PrivateClinicEntities()
            : base("name=PrivateClinicEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointment { get; set; }
        public virtual DbSet<Conclusion> Conclusion { get; set; }
        public virtual DbSet<Consultation> Consultation { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Family> Family { get; set; }
        public virtual DbSet<Inspect> Inspect { get; set; }
        public virtual DbSet<Internal> Internal { get; set; }
        public virtual DbSet<KnowledgeBase> KnowledgeBase { get; set; }
        public virtual DbSet<Marriage> Marriage { get; set; }
        public virtual DbSet<MedicalHistory> MedicalHistory { get; set; }
        public virtual DbSet<Menstrual> Menstrual { get; set; }
        public virtual DbSet<Present> Present { get; set; }
        public virtual DbSet<ReturnVisit> ReturnVisit { get; set; }
        public virtual DbSet<Surgery> Surgery { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
    }
}
