//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FershGreen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surgery
    {
        public int SurID { get; set; }
        public Nullable<int> SurHeight { get; set; }
        public Nullable<int> SurBust { get; set; }
        public Nullable<int> SurWeight { get; set; }
        public string SurFace { get; set; }
        public string SurNeck { get; set; }
        public string SurSpine { get; set; }
        public string SurLimb { get; set; }
        public string SurJoint { get; set; }
        public string SurOther { get; set; }
        public int SInID { get; set; }
    
        public virtual Inspect Inspect { get; set; }
    }
}
